# Generated by Django 3.2.3 on 2021-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('authtoken', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentMeetinglog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtoken', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('uiud', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('jointime', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('authtoken', models.CharField(max_length=100)),
            ],
        ),
    ]
