# Generated by Django 3.2.3 on 2021-05-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtoken', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=500)),
                ('report', models.TextField()),
            ],
        ),
    ]
