# Generated by Django 3.2.3 on 2021-05-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_reportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('late', models.CharField(max_length=100)),
                ('leftearly', models.CharField(max_length=100)),
                ('minduration', models.CharField(max_length=100)),
            ],
        ),
    ]
