# Generated by Django 3.2.3 on 2021-05-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_metrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlog',
            old_name='authtoken',
            new_name='username',
        ),
    ]
